name: Laravel deploy DEVELOP

on:
  push:
    branches:
      - develop

jobs:
  tests:
    uses: ./.github/workflows/run-tests.yml
  deploy:
    name: Deploy
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - name: Info
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTDEV }}
          username: ${{ secrets.USERNAMEDEV }}
          port: ${{ secrets.PORTDEV }}
          key: ${{ secrets.SSHKEYDEV }}
          script: "cd /root/html/dem && git pull && docker exec php81_dem bash scripts/deploy_dev.sh"
